### ISSUE TITLE
UX Changes after first feedback round

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-wizard#100]
## Make the Raiden Wizard easy to use 

- [x] **General:** include more documentation, in order for a “unexperienced” user to understand what he/she is doing and what the steps are - possibly a tracker re. the steps. , i.e. explain them initially and then show via a tracker the current step

This is the initial explanation on the first page 
![Raiden Wizard Explain - first page](https://user-images.githubusercontent.com/35031754/79965182-0016bf00-848c-11ea-9f60-90ab7e8fa3f7.jpg)

- [x] **General:** Show explanation when you scroll over a button, what that button does. Try to reduce as much text shown as possible. We want a very clean design. 
- [x] **General:** get data for FIAT balances, whenever balances are involved (user sees $ or EUR) - **not possible, prices are not available for free via API**

**We need a redesign of the wizard pages - we need only 6 pages (for a first time user)**
---- 
**First Page**: See explanatory picture and accept disclaimer
![Page-1](https://user-images.githubusercontent.com/35031754/79975155-d31dd880-849a-11ea-8380-c1a88e273a3f.png)

- [x] Replace header "Goerli Wizard" to "Raiden Wizard"
- [x] Add the disclaimer with links to all services and their disclaimer but hidden. So we want to see only a checkbox and some text [use placeholder text @manuelwedler ]. The correct disclaimer should be shown after clicking a link in a separate pop-up [use placeholder text @manuelwedler ]
- [x] Remove dropdown "mainnet / goerli" - we only want mainnet for now
- [x] Show less text and tell the user that it takes 5 steps but not which

---- 
**Second Page**: Connecting to the Ethereum Blockchain
![Page-2](https://user-images.githubusercontent.com/35031754/79975168-da44e680-849a-11ea-92b4-150a044342c9.png)

- [x] Less text - write only "Provide your Infura ID"
- [x] An (i) icon should after Infura should link to an official page of Infura explaining it.
- [x] Rename headline to "Connect to the Ethereum Blockchain"

---- 
**Third Page**: Send ETH to your newly created wallet

![Page-3](https://user-images.githubusercontent.com/35031754/79975248-f6e11e80-849a-11ea-9f6e-1c8a2b4a1365.png)

**We need to redesign that page** - goal of the page is to have a wallet with the min required amount of ETH. This wallet is recoverable with a passphrase. If the user wants to know how, she get's the information

- [x] Add simple button to connect to Metamask and send ETH to newly created address 
- [x] When min amount of ETH is detected in wallet, user will be redirected to fourth page
- [x] Add text, something like: "We generated a wallet for you"
- [x] When hovering over "wallet" a box should show a tooltip described in https://github.com/raiden-network/raiden-wizard/issues/130:
- [x] Private key should not be visible / copyable, see https://github.com/raiden-network/raiden-wizard/issues/134

---- 
**Fourth Page**: Swap ETH to RDN
![Page-4](https://user-images.githubusercontent.com/35031754/79976065-525fdc00-849c-11ea-9cc0-c1ad473f5922.png)
![Page-4-new](https://user-images.githubusercontent.com/35031754/79976481-fb0e3b80-849c-11ea-8843-03159eea2eec.png)
![Page4-oldswap](https://user-images.githubusercontent.com/35031754/79979422-c6e94980-84a1-11ea-9a55-2bb02ae25e95.png)

**We need to redesign and merge those 3 pages** - Goal of the new page is to swap ETH to the min required amount of RDN. 
- [x] Re-design the whole page - delete existing content :)
- [x] User can choose which DEX to be used. Add icons for DEXes UniSwap and Kyber
- [x] If DEX is chosen, view is expanded. Users sees 3 Buttons (10 RDN, 20 RDN, 50 RDN)
- [x] The user sees price for swap and all conditions inside the buttons, see https://github.com/raiden-network/raiden-wizard/issues/133
- [x] Click on continue button executes swap

---- 
**Fifth Page**: Swap ETH to DAI
![Page-4](https://user-images.githubusercontent.com/35031754/79976065-525fdc00-849c-11ea-9cc0-c1ad473f5922.png)
![Page5-new](https://user-images.githubusercontent.com/35031754/79977623-dd41d600-849e-11ea-8e83-3170c4a8e592.png)
![Page5-oldswap](https://user-images.githubusercontent.com/35031754/79977629-e03cc680-849e-11ea-9656-ceb561e9bdf0.png)

**We need to redesign and merge those 3 pages** - Goal of the new page is to swap ETH to the min required amount of DAI. 
- [x] Re-design the whole page - delete existing content :)
- [x] User can choose which DEX to be used. Add icons for DEXes UniSwap and Kyber
- [x] If DEX is chosen, view is expanded. Users sees 3 Buttons (2 DAI, 5 DAI, 10 DAI)
- [x] The user sees price for swap and all conditions inside the buttons, see https://github.com/raiden-network/raiden-wizard/issues/133
- [x] Click on continue button executes swap

---- 
**Sixth Page**: Start Raiden
![Page-6](https://user-images.githubusercontent.com/35031754/79977858-41649a00-849f-11ea-96a7-d8b26145f178.png)

- [x] The user should be shown discretely her current balance 
- [x] We need only one button "Launch Raiden" - the user should be somehow informed how long that will take

----
- [x] also see https://github.com/raiden-network/raiden-wizard/issues/109

- **Legal:** Propose one legal disclaimer that entails everything and get approval from Jim (Maybe we can use the new bbtech lawyer here?)

**Comment by Dominik1999** [comment]
Still missing: How is the user flow, if Wizard was used before?

**Comment by konradkonrad** [comment]
Suggestion: while waiting for on-chain transactions, we could display an `iframe` with the transaction view on etherscan (`https://etherscan.io/<txhash>`).
That way the user gets good feedback on the status of the transaction and we don't rely only on our status handling.

**Comment by konradkonrad** [comment]
Please also give https://github.com/raiden-network/raiden-wizard/issues/123 some consideration!

**Comment by konradkonrad** [comment]
There is also this suggestion: https://github.com/raiden-network/raiden-wizard/issues/117#issuecomment-619929420

**Comment by Dominik1999** [comment]
all done
