### ISSUE TITLE
[META] Feedback from demo 05/05/20 and 05/06/20 and 05/12/20

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-wizard#158]
Here are the most important feedback from the demo with kamal:

Paul's and Kamal's feedback for macOC
- [x] **Enhancement:** codesign binaries for Mac? #204 
- [x] **Bug:** generating wallet did not work - @fredo has already a PR #170 
- [x] **UX:** It is not clear where the Infura ID is or what to use from infura
- [x] **UX:** tell user how long it will take at the beginning and give more info about the steps
- [x] **UX:** tell why 0.18 ETH are needed #176 
- [x] **UX:** not show "send ETH" before Raiden Account was downloaded? (The Download Button for the Wallet is easiliy overseen) #177 
- [x] **Enhancement:** Metamask was set with the wrong account and the wizard tries automatically to send the money from that account - *not fixable*
- [x] **UX:** how many tokens needed of RDN or DAI? No one understands this #191
- [x] **UX:** Paul & Kamal didn't see the confirm button #178
- [x] **UX:** waiting for the exchange gives information which might be unnecessary, and better information would be nice suche as waiting time estimation (e.g. this may take a while be patient - or a youtube video about Raiden can be shown)
- [x] **UX:** Paul didn't get that RDN swap was successful - get the ticker (e.g. "step 3/5 - now you need DAI" back - *in progress*
- [x] **UX:** Swap logging change "trying to acquire up to" to " you get exactly" #192
- [x] **Bug:** after exchanging for DAI it returned to the swap DAI page, not the the launch raiden page (first run of Kamal Tuesday)
- [x] **Bug:** When depositing we received a "Nonce too low" error (first run of Kamal Tuesday) #192
- [x] **Enhancement:** skip first allowance of the UDC for first run depositing into the UDC takes long time #192
- [x] **Bug:** unclear how to stop it, see #37   - *done by webui*
Some follow ups from #109 
- [x]  **UX:** I need to click twice on `Send 0.02 ETH` (first connect in metamask, then send) --> how about a `Connect` Button and a `Send` Button? (Probably better to have separate Buttons than changing the caption after connect)
- [x] **UX:** confirmation notification from metamask sees it, but funding screen is still waiting

Open questions from users:

- should we already join DAI token network? (Ask every user what she thinks and then we decide)
- what happens when the user clicks the "back"-button on the browser

**Comment by fredo** [comment]
It might be possible that some of the errors happened due to clicking twice on a button. How could we mitigate such a problem? 
Keep in mind that the backend is supposed to be completely stateless. 
Maybe the user clicked twice due to slow reaction time of the UI?

**Comment by Dominik1999** [comment]
- how many token needed? No ons understand this?
- wrong address?
- Paul didn't see the confirm button
- Paul didn't get that RDN swap changed

**Comment by konradkonrad** [comment]
Some follow ups from #109 
- [ ]  **UX:** I need to click twice on `Send 0.02 ETH` (first connect in metamask, then send) --> how about a `Connect` Button and a `Send` Button? (Probably better to have separate Buttons than changing the caption after connect)
- [ ] **UX:** confirmation notification from metamask sees it, but funding screen is still waiting
- [ ] **UX:** how can I cancel the KYBER swap (before executing)? Back button?

**Comment by Dominik1999** [comment]
- next time make binaries 1h before the demo
- need to allow access (make it an executable)
- add flow at the first page again
- don't show transaction hash it is too long & confusing (maybe hide it?)
- 3 icons but 6 steps
- text and spinner are too close
- did not increase the gas price in Talel's run
- user needs feedback what to do with a transaction that is spinning for a long time (link to etherscan)
- user doesn't know how many tokens are needed -> just offer 1 amount? Don't let the user chose
- cost estimate before swapping (should be faster now?)
- make amounts different color than text
- Talel did not understand difference SWAP RDN and SWAP DAI (write in the title step 5/6?)
- Always write Raiden in upper case
- Every Text bigger than 12px 
- view the passphrase when you chose it -> see it in plain text
- provide infura id (not to run the node)
- download wallet main purpose, main action was quite hidden
- What is the user waiting for during a transaction -> more explanation for the user
- we need a process for users shutting down the browser or clicking the back-button
Sohans points (might be duplicates)
- Integrate a link for tx_hash to etherscan
- Wizard fast transaction(1 gwei transaction)
- different colours for the amounts and message while swapping in the spinner
- moves step information to the title
- View the password
- download main action hidden
- handle Accidental shutdown
- importing a funded keystore json file

**Comment by Dominik1999** [comment]
Feedback Boris Run:

- clicking the Wizard does not work
- user needs to make it an executable
- Boris needed to run as admin
- We need to create binaries on an old Linux
