### ISSUE TITLE
[Feature] Make wizard compatible with demoenvironments

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden-wizard#96]
## Idea
Since the Wizard is part of our solution bundle that simplifies onboarding it does make a lot of sense to provide a wizard version that setups a raiden node using the demo environment.

## Suggestion
Create a config / constant file for the wizard to easily change different setup variables for the wizard. (All required changeable variables are listed underneath)

## TODO
Simplify the deployment of a raiden wizard version that setups raiden using the demo environment
- [x] Make it easy to change Raiden binary download link
- [x] Make it easy to change the Raiden config file (pfs/ms server, matrix server, routing mode)
- [x] Automize minting of correct SVT tokens (Every Raiden Smart contract release deploys it's own SVT) --> Also approval (with the SVT contract) and deposit to UDC should be automized

**Comment by eorituz** [comment]
PR #106 targets all of the above bullet points more or less.
I was able to deploy a raiden wizard version that works and uses a "demoenv" (Since we don't have a demo environment yet I used a test environment).

However, every new version of the raiden smartcontracts requires some manual changes to the wizard code. This is targeted in Issue #104.

@Dominik1999 please assign someone to review my PR when you guys find the time
